export const PermissionsList = {
    CrearRoles: '1z9Sv2fC1ALXdM80L0QHs9c3HLDoAOO8',
    ModuloEmpleados: '8QnE1cYkjjNAmM7qHSf1CSlPMJiQeqr5',
    AdminPersonalActivo: 'dmcnXs5gK1qHzn30WvGXDzFimcrVJZ9Z',
    SeleccionarPermiso: 'G8aCoYYCgE8fAwegn0MvWjxMXhxIIrhy',
    CrearUsuarios: 'lJFsnYJCnFcVPVBBUOQrmlv3b6Y2X2ZE',
    SeleccionarRol: 'm0D4LIsO7V79aDueMDjgWGOmp8mPW6c0',
    EliminarUsuarios: 'n5TraVIrRoioG1kqdHsIaZLYDvxO8MFD',
    VerRoles: 'nrPqEhq2TX0mI7qT7glaOCJ7Iqx2QtPs',
    VerUsuarios: 'nTSk4Y4SFKMyQmRD4ku0UCiNWIDe8OEt',
    EliminarRoles: 'QpKVz00WUbZVJMPFu3iBNGBTdMFYubQ2',
    CRUDPermisos: 'RGMUpFAiRuv7UFoJroHP6CtvmpoFlQXl',
    EditarRoles: 'v216XcAzgbt4mIjj6gZP2rdRTupXz0AO',
    EditarUsuarios: 'W8Xmv3hiIyIpkZfJMaL9MsRxxuSIiO5R',
    ReportesQuery: '6ARHQGj1N8YPkr02DY04K1Zy7HjIdDcj',
}